set(FLAT_ROOT_DIR       "${CMAKE_SOURCE_DIR}"                   CACHE INTERNAL "")
set(FLAT_INCLUDE_DIR    "${FLAT_ROOT_DIR}/include"              CACHE INTERNAL "")
set(FLAT_SOURCE_DIR     "${FLAT_ROOT_DIR}/src"                  CACHE INTERNAL "")
set(FLAT_VENDOR_DIR     "${FLAT_ROOT_DIR}/vendor"               CACHE INTERNAL "")
set(FLAT_PROJECT_DIR    "${FLAT_ROOT_DIR}/project"              CACHE INTERNAL "")
set(FLAT_BIN_DIR        "${FLAT_ROOT_DIR}/bin"                  CACHE INTERNAL "")
set(FLAT_BIN_CONFIG_DIR "${FLAT_BIN_DIR}/${FLAT_CONFIG_STRING}" CACHE INTERNAL "")


set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${FLAT_BIN_CONFIG_DIR}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${FLAT_BIN_CONFIG_DIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${FLAT_BIN_CONFIG_DIR}")